// Code generated by a tool. DO NOT EDIT.

// Package bufio provides a mockable wrapper for bufio.
package bufio

import (
	bufio "bufio"
	io "io"
)

var _ Interface = &Impl{}
var _ = bufio.NewReadWriter

type Interface interface {
	NewReadWriter(r *bufio.Reader, w *bufio.Writer) *bufio.ReadWriter
	NewReader(rd io.Reader) *bufio.Reader
	NewReaderSize(rd io.Reader, size int) *bufio.Reader
	NewScanner(r io.Reader) *bufio.Scanner
	NewWriter(w io.Writer) *bufio.Writer
	NewWriterSize(w io.Writer, size int) *bufio.Writer
	ScanBytes(data []byte, atEOF bool) (advance int, token []byte, err error)
	ScanLines(data []byte, atEOF bool) (advance int, token []byte, err error)
	ScanRunes(data []byte, atEOF bool) (advance int, token []byte, err error)
	ScanWords(data []byte, atEOF bool) (advance int, token []byte, err error)
}

type Impl struct{}

func (*Impl) NewReadWriter(r *bufio.Reader, w *bufio.Writer) *bufio.ReadWriter {
	return bufio.NewReadWriter(r, w)
}
func (*Impl) NewReader(rd io.Reader) *bufio.Reader {
	return bufio.NewReader(rd)
}
func (*Impl) NewReaderSize(rd io.Reader, size int) *bufio.Reader {
	return bufio.NewReaderSize(rd, size)
}
func (*Impl) NewScanner(r io.Reader) *bufio.Scanner {
	return bufio.NewScanner(r)
}
func (*Impl) NewWriter(w io.Writer) *bufio.Writer {
	return bufio.NewWriter(w)
}
func (*Impl) NewWriterSize(w io.Writer, size int) *bufio.Writer {
	return bufio.NewWriterSize(w, size)
}
func (*Impl) ScanBytes(data []byte, atEOF bool) (advance int, token []byte, err error) {
	return bufio.ScanBytes(data, atEOF)
}
func (*Impl) ScanLines(data []byte, atEOF bool) (advance int, token []byte, err error) {
	return bufio.ScanLines(data, atEOF)
}
func (*Impl) ScanRunes(data []byte, atEOF bool) (advance int, token []byte, err error) {
	return bufio.ScanRunes(data, atEOF)
}
func (*Impl) ScanWords(data []byte, atEOF bool) (advance int, token []byte, err error) {
	return bufio.ScanWords(data, atEOF)
}
