// Code generated by a tool. DO NOT EDIT.

// Package sha256 provides a mockable wrapper for crypto/sha256.
package sha256

import (
	sha256 "crypto/sha256"
	hash "hash"
)

var _ Interface = &Impl{}
var _ = sha256.New

type Interface interface {
	New() hash.Hash
	New224() hash.Hash
	Sum224(data []byte) [28]byte
	Sum256(data []byte) [32]byte
}

type Impl struct{}

func (*Impl) New() hash.Hash {
	return sha256.New()
}
func (*Impl) New224() hash.Hash {
	return sha256.New224()
}
func (*Impl) Sum224(data []byte) [28]byte {
	return sha256.Sum224(data)
}
func (*Impl) Sum256(data []byte) [32]byte {
	return sha256.Sum256(data)
}
