// Code generated by a tool. DO NOT EDIT.

// Package scanner provides a mockable wrapper for text/scanner.
package scanner

import (
	scanner "text/scanner"
)

var _ Interface = &Impl{}
var _ = scanner.TokenString

type Interface interface {
	TokenString(tok rune) string
}

type Impl struct{}

func (*Impl) TokenString(tok rune) string {
	return scanner.TokenString(tok)
}
