// Code generated by a tool. DO NOT EDIT.

// Package token provides a mockable wrapper for go/token.
package token

import (
	token "go/token"
)

var _ Interface = &Impl{}
var _ = token.IsExported

type Interface interface {
	IsExported(name string) bool
	IsIdentifier(name string) bool
	IsKeyword(name string) bool
	Lookup(ident string) token.Token
	NewFileSet() *token.FileSet
}

type Impl struct{}

func (*Impl) IsExported(name string) bool {
	return token.IsExported(name)
}
func (*Impl) IsIdentifier(name string) bool {
	return token.IsIdentifier(name)
}
func (*Impl) IsKeyword(name string) bool {
	return token.IsKeyword(name)
}
func (*Impl) Lookup(ident string) token.Token {
	return token.Lookup(ident)
}
func (*Impl) NewFileSet() *token.FileSet {
	return token.NewFileSet()
}
