// Code generated by a tool. DO NOT EDIT.

// Package base64 provides a mockable wrapper for encoding/base64.
package base64

import (
	base64 "encoding/base64"
	io "io"
)

var _ Interface = &Impl{}
var _ = base64.NewDecoder

type Interface interface {
	NewDecoder(enc *base64.Encoding, r io.Reader) io.Reader
	NewEncoder(enc *base64.Encoding, w io.Writer) io.WriteCloser
	NewEncoding(encoder string) *base64.Encoding
}

type Impl struct{}

func (*Impl) NewDecoder(enc *base64.Encoding, r io.Reader) io.Reader {
	return base64.NewDecoder(enc, r)
}
func (*Impl) NewEncoder(enc *base64.Encoding, w io.Writer) io.WriteCloser {
	return base64.NewEncoder(enc, w)
}
func (*Impl) NewEncoding(encoder string) *base64.Encoding {
	return base64.NewEncoding(encoder)
}
