// Code generated by a tool. DO NOT EDIT.

// Package png provides a mockable wrapper for image/png.
package png

import (
	image "image"
	png "image/png"
	io "io"
)

var _ Interface = &Impl{}
var _ = png.Decode

type Interface interface {
	Decode(r io.Reader) (image.Image, error)
	DecodeConfig(r io.Reader) (image.Config, error)
	Encode(w io.Writer, m image.Image) error
}

type Impl struct{}

func (*Impl) Decode(r io.Reader) (image.Image, error) {
	return png.Decode(r)
}
func (*Impl) DecodeConfig(r io.Reader) (image.Config, error) {
	return png.DecodeConfig(r)
}
func (*Impl) Encode(w io.Writer, m image.Image) error {
	return png.Encode(w, m)
}
