// Code generated by a tool. DO NOT EDIT.

// Package httptest provides a mockable wrapper for net/http/httptest.
package httptest

import (
	io "io"
	http "net/http"
	httptest "net/http/httptest"
)

var _ Interface = &Impl{}
var _ = httptest.NewRecorder

type Interface interface {
	NewRecorder() *httptest.ResponseRecorder
	NewRequest(method string, target string, body io.Reader) *http.Request
	NewServer(handler http.Handler) *httptest.Server
	NewTLSServer(handler http.Handler) *httptest.Server
	NewUnstartedServer(handler http.Handler) *httptest.Server
}

type Impl struct{}

func (*Impl) NewRecorder() *httptest.ResponseRecorder {
	return httptest.NewRecorder()
}
func (*Impl) NewRequest(method string, target string, body io.Reader) *http.Request {
	return httptest.NewRequest(method, target, body)
}
func (*Impl) NewServer(handler http.Handler) *httptest.Server {
	return httptest.NewServer(handler)
}
func (*Impl) NewTLSServer(handler http.Handler) *httptest.Server {
	return httptest.NewTLSServer(handler)
}
func (*Impl) NewUnstartedServer(handler http.Handler) *httptest.Server {
	return httptest.NewUnstartedServer(handler)
}
