// Code generated by a tool. DO NOT EDIT.

// Package cookiejar provides a mockable wrapper for net/http/cookiejar.
package cookiejar

import (
	cookiejar "net/http/cookiejar"
)

var _ Interface = &Impl{}
var _ = cookiejar.New

type Interface interface {
	New(o *cookiejar.Options) (*cookiejar.Jar, error)
}

type Impl struct{}

func (*Impl) New(o *cookiejar.Options) (*cookiejar.Jar, error) {
	return cookiejar.New(o)
}
