// Code generated by a tool. DO NOT EDIT.

// Package tar provides a mockable wrapper for archive/tar.
package tar

import (
	tar "archive/tar"
	io "io"
	fs "io/fs"
)

var _ Interface = &Impl{}
var _ = tar.FileInfoHeader

type Interface interface {
	FileInfoHeader(fi fs.FileInfo, link string) (*tar.Header, error)
	NewReader(r io.Reader) *tar.Reader
	NewWriter(w io.Writer) *tar.Writer
}

type Impl struct{}

func (*Impl) FileInfoHeader(fi fs.FileInfo, link string) (*tar.Header, error) {
	return tar.FileInfoHeader(fi, link)
}
func (*Impl) NewReader(r io.Reader) *tar.Reader {
	return tar.NewReader(r)
}
func (*Impl) NewWriter(w io.Writer) *tar.Writer {
	return tar.NewWriter(w)
}
