// Code generated by a tool. DO NOT EDIT.

// Package draw provides a mockable wrapper for image/draw.
package draw

import (
	image "image"
	draw "image/draw"
)

var _ Interface = &Impl{}
var _ = draw.Draw

type Interface interface {
	Draw(dst draw.Image, r image.Rectangle, src image.Image, sp image.Point, op draw.Op)
	DrawMask(dst draw.Image, r image.Rectangle, src image.Image, sp image.Point, mask image.Image, mp image.Point, op draw.Op)
}

type Impl struct{}

func (*Impl) Draw(dst draw.Image, r image.Rectangle, src image.Image, sp image.Point, op draw.Op) {
	draw.Draw(dst, r, src, sp, op)
}
func (*Impl) DrawMask(dst draw.Image, r image.Rectangle, src image.Image, sp image.Point, mask image.Image, mp image.Point, op draw.Op) {
	draw.DrawMask(dst, r, src, sp, mask, mp, op)
}
