// Code generated by a tool. DO NOT EDIT.

// Package gif provides a mockable wrapper for image/gif.
package gif

import (
	image "image"
	gif "image/gif"
	io "io"
)

var _ Interface = &Impl{}
var _ = gif.Decode

type Interface interface {
	Decode(r io.Reader) (image.Image, error)
	DecodeAll(r io.Reader) (*gif.GIF, error)
	DecodeConfig(r io.Reader) (image.Config, error)
	Encode(w io.Writer, m image.Image, o *gif.Options) error
	EncodeAll(w io.Writer, g *gif.GIF) error
}

type Impl struct{}

func (*Impl) Decode(r io.Reader) (image.Image, error) {
	return gif.Decode(r)
}
func (*Impl) DecodeAll(r io.Reader) (*gif.GIF, error) {
	return gif.DecodeAll(r)
}
func (*Impl) DecodeConfig(r io.Reader) (image.Config, error) {
	return gif.DecodeConfig(r)
}
func (*Impl) Encode(w io.Writer, m image.Image, o *gif.Options) error {
	return gif.Encode(w, m, o)
}
func (*Impl) EncodeAll(w io.Writer, g *gif.GIF) error {
	return gif.EncodeAll(w, g)
}
