// Code generated by a tool. DO NOT EDIT.

// Package metrics provides a mockable wrapper for runtime/metrics.
package metrics

import (
	metrics "runtime/metrics"
)

var _ Interface = &Impl{}
var _ = metrics.All

type Interface interface {
	All() []metrics.Description
	Read(m []metrics.Sample)
}

type Impl struct{}

func (*Impl) All() []metrics.Description {
	return metrics.All()
}
func (*Impl) Read(m []metrics.Sample) {
	metrics.Read(m)
}
