// Code generated by a tool. DO NOT EDIT.

// Package cgi provides a mockable wrapper for net/http/cgi.
package cgi

import (
	http "net/http"
	cgi "net/http/cgi"
)

var _ Interface = &Impl{}
var _ = cgi.Request

type Interface interface {
	Request() (*http.Request, error)
	RequestFromMap(params map[string]string) (*http.Request, error)
	Serve(handler http.Handler) error
}

type Impl struct{}

func (*Impl) Request() (*http.Request, error) {
	return cgi.Request()
}
func (*Impl) RequestFromMap(params map[string]string) (*http.Request, error) {
	return cgi.RequestFromMap(params)
}
func (*Impl) Serve(handler http.Handler) error {
	return cgi.Serve(handler)
}
