// Code generated by a tool. DO NOT EDIT.

// Package math provides a mockable wrapper for math.
package math

import (
	math "math"
)

var _ Interface = &Impl{}
var _ = math.Abs

type Interface interface {
	Abs(x float64) float64
	Acos(x float64) float64
	Acosh(x float64) float64
	Asin(x float64) float64
	Asinh(x float64) float64
	Atan(x float64) float64
	Atan2(y float64, x float64) float64
	Atanh(x float64) float64
	Cbrt(x float64) float64
	Ceil(x float64) float64
	Copysign(x float64, y float64) float64
	Cos(x float64) float64
	Cosh(x float64) float64
	Dim(x float64, y float64) float64
	Erf(x float64) float64
	Erfc(x float64) float64
	Erfcinv(x float64) float64
	Erfinv(x float64) float64
	Exp(x float64) float64
	Exp2(x float64) float64
	Expm1(x float64) float64
	FMA(x float64, y float64, z float64) float64
	Float32bits(f float32) uint32
	Float32frombits(b uint32) float32
	Float64bits(f float64) uint64
	Float64frombits(b uint64) float64
	Floor(x float64) float64
	Frexp(f float64) (frac float64, exp int)
	Gamma(x float64) float64
	Hypot(p float64, q float64) float64
	Ilogb(x float64) int
	Inf(sign int) float64
	IsInf(f float64, sign int) bool
	IsNaN(f float64) (is bool)
	J0(x float64) float64
	J1(x float64) float64
	Jn(n int, x float64) float64
	Ldexp(frac float64, exp int) float64
	Lgamma(x float64) (lgamma float64, sign int)
	Log(x float64) float64
	Log10(x float64) float64
	Log1p(x float64) float64
	Log2(x float64) float64
	Logb(x float64) float64
	Max(x float64, y float64) float64
	Min(x float64, y float64) float64
	Mod(x float64, y float64) float64
	Modf(f float64) (int float64, frac float64)
	NaN() float64
	Nextafter(x float64, y float64) (r float64)
	Nextafter32(x float32, y float32) (r float32)
	Pow(x float64, y float64) float64
	Pow10(n int) float64
	Remainder(x float64, y float64) float64
	Round(x float64) float64
	RoundToEven(x float64) float64
	Signbit(x float64) bool
	Sin(x float64) float64
	Sincos(x float64) (sin float64, cos float64)
	Sinh(x float64) float64
	Sqrt(x float64) float64
	Tan(x float64) float64
	Tanh(x float64) float64
	Trunc(x float64) float64
	Y0(x float64) float64
	Y1(x float64) float64
	Yn(n int, x float64) float64
}

type Impl struct{}

func (*Impl) Abs(x float64) float64 {
	return math.Abs(x)
}
func (*Impl) Acos(x float64) float64 {
	return math.Acos(x)
}
func (*Impl) Acosh(x float64) float64 {
	return math.Acosh(x)
}
func (*Impl) Asin(x float64) float64 {
	return math.Asin(x)
}
func (*Impl) Asinh(x float64) float64 {
	return math.Asinh(x)
}
func (*Impl) Atan(x float64) float64 {
	return math.Atan(x)
}
func (*Impl) Atan2(y float64, x float64) float64 {
	return math.Atan2(y, x)
}
func (*Impl) Atanh(x float64) float64 {
	return math.Atanh(x)
}
func (*Impl) Cbrt(x float64) float64 {
	return math.Cbrt(x)
}
func (*Impl) Ceil(x float64) float64 {
	return math.Ceil(x)
}
func (*Impl) Copysign(x float64, y float64) float64 {
	return math.Copysign(x, y)
}
func (*Impl) Cos(x float64) float64 {
	return math.Cos(x)
}
func (*Impl) Cosh(x float64) float64 {
	return math.Cosh(x)
}
func (*Impl) Dim(x float64, y float64) float64 {
	return math.Dim(x, y)
}
func (*Impl) Erf(x float64) float64 {
	return math.Erf(x)
}
func (*Impl) Erfc(x float64) float64 {
	return math.Erfc(x)
}
func (*Impl) Erfcinv(x float64) float64 {
	return math.Erfcinv(x)
}
func (*Impl) Erfinv(x float64) float64 {
	return math.Erfinv(x)
}
func (*Impl) Exp(x float64) float64 {
	return math.Exp(x)
}
func (*Impl) Exp2(x float64) float64 {
	return math.Exp2(x)
}
func (*Impl) Expm1(x float64) float64 {
	return math.Expm1(x)
}
func (*Impl) FMA(x float64, y float64, z float64) float64 {
	return math.FMA(x, y, z)
}
func (*Impl) Float32bits(f float32) uint32 {
	return math.Float32bits(f)
}
func (*Impl) Float32frombits(b uint32) float32 {
	return math.Float32frombits(b)
}
func (*Impl) Float64bits(f float64) uint64 {
	return math.Float64bits(f)
}
func (*Impl) Float64frombits(b uint64) float64 {
	return math.Float64frombits(b)
}
func (*Impl) Floor(x float64) float64 {
	return math.Floor(x)
}
func (*Impl) Frexp(f float64) (frac float64, exp int) {
	return math.Frexp(f)
}
func (*Impl) Gamma(x float64) float64 {
	return math.Gamma(x)
}
func (*Impl) Hypot(p float64, q float64) float64 {
	return math.Hypot(p, q)
}
func (*Impl) Ilogb(x float64) int {
	return math.Ilogb(x)
}
func (*Impl) Inf(sign int) float64 {
	return math.Inf(sign)
}
func (*Impl) IsInf(f float64, sign int) bool {
	return math.IsInf(f, sign)
}
func (*Impl) IsNaN(f float64) (is bool) {
	return math.IsNaN(f)
}
func (*Impl) J0(x float64) float64 {
	return math.J0(x)
}
func (*Impl) J1(x float64) float64 {
	return math.J1(x)
}
func (*Impl) Jn(n int, x float64) float64 {
	return math.Jn(n, x)
}
func (*Impl) Ldexp(frac float64, exp int) float64 {
	return math.Ldexp(frac, exp)
}
func (*Impl) Lgamma(x float64) (lgamma float64, sign int) {
	return math.Lgamma(x)
}
func (*Impl) Log(x float64) float64 {
	return math.Log(x)
}
func (*Impl) Log10(x float64) float64 {
	return math.Log10(x)
}
func (*Impl) Log1p(x float64) float64 {
	return math.Log1p(x)
}
func (*Impl) Log2(x float64) float64 {
	return math.Log2(x)
}
func (*Impl) Logb(x float64) float64 {
	return math.Logb(x)
}
func (*Impl) Max(x float64, y float64) float64 {
	return math.Max(x, y)
}
func (*Impl) Min(x float64, y float64) float64 {
	return math.Min(x, y)
}
func (*Impl) Mod(x float64, y float64) float64 {
	return math.Mod(x, y)
}
func (*Impl) Modf(f float64) (int float64, frac float64) {
	return math.Modf(f)
}
func (*Impl) NaN() float64 {
	return math.NaN()
}
func (*Impl) Nextafter(x float64, y float64) (r float64) {
	return math.Nextafter(x, y)
}
func (*Impl) Nextafter32(x float32, y float32) (r float32) {
	return math.Nextafter32(x, y)
}
func (*Impl) Pow(x float64, y float64) float64 {
	return math.Pow(x, y)
}
func (*Impl) Pow10(n int) float64 {
	return math.Pow10(n)
}
func (*Impl) Remainder(x float64, y float64) float64 {
	return math.Remainder(x, y)
}
func (*Impl) Round(x float64) float64 {
	return math.Round(x)
}
func (*Impl) RoundToEven(x float64) float64 {
	return math.RoundToEven(x)
}
func (*Impl) Signbit(x float64) bool {
	return math.Signbit(x)
}
func (*Impl) Sin(x float64) float64 {
	return math.Sin(x)
}
func (*Impl) Sincos(x float64) (sin float64, cos float64) {
	return math.Sincos(x)
}
func (*Impl) Sinh(x float64) float64 {
	return math.Sinh(x)
}
func (*Impl) Sqrt(x float64) float64 {
	return math.Sqrt(x)
}
func (*Impl) Tan(x float64) float64 {
	return math.Tan(x)
}
func (*Impl) Tanh(x float64) float64 {
	return math.Tanh(x)
}
func (*Impl) Trunc(x float64) float64 {
	return math.Trunc(x)
}
func (*Impl) Y0(x float64) float64 {
	return math.Y0(x)
}
func (*Impl) Y1(x float64) float64 {
	return math.Y1(x)
}
func (*Impl) Yn(n int, x float64) float64 {
	return math.Yn(n, x)
}
