// Code generated by a tool. DO NOT EDIT.

// Package url provides a mockable wrapper for net/url.
package url

import (
	url "net/url"
)

var _ Interface = &Impl{}
var _ = url.Parse

type Interface interface {
	Parse(rawURL string) (*url.URL, error)
	ParseQuery(query string) (url.Values, error)
	ParseRequestURI(rawURL string) (*url.URL, error)
	PathEscape(s string) string
	PathUnescape(s string) (string, error)
	QueryEscape(s string) string
	QueryUnescape(s string) (string, error)
	User(username string) *url.Userinfo
	UserPassword(username string, password string) *url.Userinfo
}

type Impl struct{}

func (*Impl) Parse(rawURL string) (*url.URL, error) {
	return url.Parse(rawURL)
}
func (*Impl) ParseQuery(query string) (url.Values, error) {
	return url.ParseQuery(query)
}
func (*Impl) ParseRequestURI(rawURL string) (*url.URL, error) {
	return url.ParseRequestURI(rawURL)
}
func (*Impl) PathEscape(s string) string {
	return url.PathEscape(s)
}
func (*Impl) PathUnescape(s string) (string, error) {
	return url.PathUnescape(s)
}
func (*Impl) QueryEscape(s string) string {
	return url.QueryEscape(s)
}
func (*Impl) QueryUnescape(s string) (string, error) {
	return url.QueryUnescape(s)
}
func (*Impl) User(username string) *url.Userinfo {
	return url.User(username)
}
func (*Impl) UserPassword(username string, password string) *url.Userinfo {
	return url.UserPassword(username, password)
}
