// Code generated by a tool. DO NOT EDIT.

// Package fstest provides a mockable wrapper for testing/fstest.
package fstest

import (
	fs "io/fs"
	fstest "testing/fstest"
)

var _ Interface = &Impl{}
var _ = fstest.TestFS

type Interface interface {
	TestFS(fsys fs.FS, expected ...string) error
}

type Impl struct{}

func (*Impl) TestFS(fsys fs.FS, expected ...string) error {
	return fstest.TestFS(fsys, expected...)
}
