// Code generated by a tool. DO NOT EDIT.

// Package rc4 provides a mockable wrapper for crypto/rc4.
package rc4

import (
	rc4 "crypto/rc4"
)

var _ Interface = &Impl{}
var _ = rc4.NewCipher

type Interface interface {
	NewCipher(key []byte) (*rc4.Cipher, error)
}

type Impl struct{}

func (*Impl) NewCipher(key []byte) (*rc4.Cipher, error) {
	return rc4.NewCipher(key)
}
