// Code generated by a tool. DO NOT EDIT.

// Package csv provides a mockable wrapper for encoding/csv.
package csv

import (
	csv "encoding/csv"
	io "io"
)

var _ Interface = &Impl{}
var _ = csv.NewReader

type Interface interface {
	NewReader(r io.Reader) *csv.Reader
	NewWriter(w io.Writer) *csv.Writer
}

type Impl struct{}

func (*Impl) NewReader(r io.Reader) *csv.Reader {
	return csv.NewReader(r)
}
func (*Impl) NewWriter(w io.Writer) *csv.Writer {
	return csv.NewWriter(w)
}
