// Code generated by a tool. DO NOT EDIT.

// Package gosym provides a mockable wrapper for debug/gosym.
package gosym

import (
	gosym "debug/gosym"
)

var _ Interface = &Impl{}
var _ = gosym.NewLineTable

type Interface interface {
	NewLineTable(data []byte, text uint64) *gosym.LineTable
	NewTable(symtab []byte, pcln *gosym.LineTable) (*gosym.Table, error)
}

type Impl struct{}

func (*Impl) NewLineTable(data []byte, text uint64) *gosym.LineTable {
	return gosym.NewLineTable(data, text)
}
func (*Impl) NewTable(symtab []byte, pcln *gosym.LineTable) (*gosym.Table, error) {
	return gosym.NewTable(symtab, pcln)
}
