// Code generated by a tool. DO NOT EDIT.

// Package tabwriter provides a mockable wrapper for text/tabwriter.
package tabwriter

import (
	io "io"
	tabwriter "text/tabwriter"
)

var _ Interface = &Impl{}
var _ = tabwriter.NewWriter

type Interface interface {
	NewWriter(output io.Writer, minwidth int, tabwidth int, padding int, padchar byte, flags uint) *tabwriter.Writer
}

type Impl struct{}

func (*Impl) NewWriter(output io.Writer, minwidth int, tabwidth int, padding int, padchar byte, flags uint) *tabwriter.Writer {
	return tabwriter.NewWriter(output, minwidth, tabwidth, padding, padchar, flags)
}
