// Code generated by a tool. DO NOT EDIT.

// Package plugin provides a mockable wrapper for plugin.
package plugin

import (
	plugin "plugin"
)

var _ Interface = &Impl{}
var _ = plugin.Open

type Interface interface {
	Open(path string) (*plugin.Plugin, error)
}

type Impl struct{}

func (*Impl) Open(path string) (*plugin.Plugin, error) {
	return plugin.Open(path)
}
