// Code generated by a tool. DO NOT EDIT.

// Package base32 provides a mockable wrapper for encoding/base32.
package base32

import (
	base32 "encoding/base32"
	io "io"
)

var _ Interface = &Impl{}
var _ = base32.NewDecoder

type Interface interface {
	NewDecoder(enc *base32.Encoding, r io.Reader) io.Reader
	NewEncoder(enc *base32.Encoding, w io.Writer) io.WriteCloser
	NewEncoding(encoder string) *base32.Encoding
}

type Impl struct{}

func (*Impl) NewDecoder(enc *base32.Encoding, r io.Reader) io.Reader {
	return base32.NewDecoder(enc, r)
}
func (*Impl) NewEncoder(enc *base32.Encoding, w io.Writer) io.WriteCloser {
	return base32.NewEncoder(enc, w)
}
func (*Impl) NewEncoding(encoder string) *base32.Encoding {
	return base32.NewEncoding(encoder)
}
