// Code generated by a tool. DO NOT EDIT.

// Package asn1 provides a mockable wrapper for encoding/asn1.
package asn1

import (
	asn1 "encoding/asn1"
)

var _ Interface = &Impl{}
var _ = asn1.Marshal

type Interface interface {
	Marshal(val any) ([]byte, error)
	MarshalWithParams(val any, params string) ([]byte, error)
	Unmarshal(b []byte, val any) (rest []byte, err error)
	UnmarshalWithParams(b []byte, val any, params string) (rest []byte, err error)
}

type Impl struct{}

func (*Impl) Marshal(val any) ([]byte, error) {
	return asn1.Marshal(val)
}
func (*Impl) MarshalWithParams(val any, params string) ([]byte, error) {
	return asn1.MarshalWithParams(val, params)
}
func (*Impl) Unmarshal(b []byte, val any) (rest []byte, err error) {
	return asn1.Unmarshal(b, val)
}
func (*Impl) UnmarshalWithParams(b []byte, val any, params string) (rest []byte, err error) {
	return asn1.UnmarshalWithParams(b, val, params)
}
