// Code generated by a tool. DO NOT EDIT.

// Package quotedprintable provides a mockable wrapper for mime/quotedprintable.
package quotedprintable

import (
	io "io"
	quotedprintable "mime/quotedprintable"
)

var _ Interface = &Impl{}
var _ = quotedprintable.NewReader

type Interface interface {
	NewReader(r io.Reader) *quotedprintable.Reader
	NewWriter(w io.Writer) *quotedprintable.Writer
}

type Impl struct{}

func (*Impl) NewReader(r io.Reader) *quotedprintable.Reader {
	return quotedprintable.NewReader(r)
}
func (*Impl) NewWriter(w io.Writer) *quotedprintable.Writer {
	return quotedprintable.NewWriter(w)
}
