// Code generated by a tool. DO NOT EDIT.

// Package list provides a mockable wrapper for container/list.
package list

import (
	list "container/list"
)

var _ Interface = &Impl{}
var _ = list.New

type Interface interface {
	New() *list.List
}

type Impl struct{}

func (*Impl) New() *list.List {
	return list.New()
}
