// Code generated by a tool. DO NOT EDIT.

// Package ring provides a mockable wrapper for container/ring.
package ring

import (
	ring "container/ring"
)

var _ Interface = &Impl{}
var _ = ring.New

type Interface interface {
	New(n int) *ring.Ring
}

type Impl struct{}

func (*Impl) New(n int) *ring.Ring {
	return ring.New(n)
}
