// Code generated by a tool. DO NOT EDIT.

// Package bzip2 provides a mockable wrapper for compress/bzip2.
package bzip2

import (
	bzip2 "compress/bzip2"
	io "io"
)

var _ Interface = &Impl{}
var _ = bzip2.NewReader

type Interface interface {
	NewReader(r io.Reader) io.Reader
}

type Impl struct{}

func (*Impl) NewReader(r io.Reader) io.Reader {
	return bzip2.NewReader(r)
}
