// Code generated by a tool. DO NOT EDIT.

// Package errors provides a mockable wrapper for errors.
package errors

import (
	errors "errors"
)

var _ Interface = &Impl{}
var _ = errors.As

type Interface interface {
	As(err error, target any) bool
	Is(err error, target error) bool
	New(text string) error
	Unwrap(err error) error
}

type Impl struct{}

func (*Impl) As(err error, target any) bool {
	return errors.As(err, target)
}
func (*Impl) Is(err error, target error) bool {
	return errors.Is(err, target)
}
func (*Impl) New(text string) error {
	return errors.New(text)
}
func (*Impl) Unwrap(err error) error {
	return errors.Unwrap(err)
}
