// Code generated by a tool. DO NOT EDIT.

// Package html provides a mockable wrapper for html.
package html

import (
	html "html"
)

var _ Interface = &Impl{}
var _ = html.EscapeString

type Interface interface {
	EscapeString(s string) string
	UnescapeString(s string) string
}

type Impl struct{}

func (*Impl) EscapeString(s string) string {
	return html.EscapeString(s)
}
func (*Impl) UnescapeString(s string) string {
	return html.UnescapeString(s)
}
