// Code generated by a tool. DO NOT EDIT.

// Package sync provides a mockable wrapper for sync.
package sync

import (
	sync "sync"
)

var _ Interface = &Impl{}
var _ = sync.NewCond

type Interface interface {
	NewCond(l sync.Locker) *sync.Cond
}

type Impl struct{}

func (*Impl) NewCond(l sync.Locker) *sync.Cond {
	return sync.NewCond(l)
}
