// Code generated by a tool. DO NOT EDIT.

// Package sha512 provides a mockable wrapper for crypto/sha512.
package sha512

import (
	sha512 "crypto/sha512"
	hash "hash"
)

var _ Interface = &Impl{}
var _ = sha512.New

type Interface interface {
	New() hash.Hash
	New384() hash.Hash
	New512_224() hash.Hash
	New512_256() hash.Hash
	Sum384(data []byte) [48]byte
	Sum512(data []byte) [64]byte
	Sum512_224(data []byte) [28]byte
	Sum512_256(data []byte) [32]byte
}

type Impl struct{}

func (*Impl) New() hash.Hash {
	return sha512.New()
}
func (*Impl) New384() hash.Hash {
	return sha512.New384()
}
func (*Impl) New512_224() hash.Hash {
	return sha512.New512_224()
}
func (*Impl) New512_256() hash.Hash {
	return sha512.New512_256()
}
func (*Impl) Sum384(data []byte) [48]byte {
	return sha512.Sum384(data)
}
func (*Impl) Sum512(data []byte) [64]byte {
	return sha512.Sum512(data)
}
func (*Impl) Sum512_224(data []byte) [28]byte {
	return sha512.Sum512_224(data)
}
func (*Impl) Sum512_256(data []byte) [32]byte {
	return sha512.Sum512_256(data)
}
