// Code generated by a tool. DO NOT EDIT.

// Package fnv provides a mockable wrapper for hash/fnv.
package fnv

import (
	hash "hash"
	fnv "hash/fnv"
)

var _ Interface = &Impl{}
var _ = fnv.New128

type Interface interface {
	New128() hash.Hash
	New128a() hash.Hash
	New32() hash.Hash32
	New32a() hash.Hash32
	New64() hash.Hash64
	New64a() hash.Hash64
}

type Impl struct{}

func (*Impl) New128() hash.Hash {
	return fnv.New128()
}
func (*Impl) New128a() hash.Hash {
	return fnv.New128a()
}
func (*Impl) New32() hash.Hash32 {
	return fnv.New32()
}
func (*Impl) New32a() hash.Hash32 {
	return fnv.New32a()
}
func (*Impl) New64() hash.Hash64 {
	return fnv.New64()
}
func (*Impl) New64a() hash.Hash64 {
	return fnv.New64a()
}
