// Code generated by a tool. DO NOT EDIT.

// Package exec provides a mockable wrapper for os/exec.
package exec

import (
	context "context"
	exec "os/exec"
)

var _ Interface = &Impl{}
var _ = exec.Command

type Interface interface {
	Command(name string, arg ...string) *exec.Cmd
	CommandContext(ctx context.Context, name string, arg ...string) *exec.Cmd
	LookPath(file string) (string, error)
}

type Impl struct{}

func (*Impl) Command(name string, arg ...string) *exec.Cmd {
	return exec.Command(name, arg...)
}
func (*Impl) CommandContext(ctx context.Context, name string, arg ...string) *exec.Cmd {
	return exec.CommandContext(ctx, name, arg...)
}
func (*Impl) LookPath(file string) (string, error) {
	return exec.LookPath(file)
}
