// Code generated by a tool. DO NOT EDIT.

// Package buildinfo provides a mockable wrapper for debug/buildinfo.
package buildinfo

import (
	buildinfo "debug/buildinfo"
	io "io"
	debug "runtime/debug"
)

var _ Interface = &Impl{}
var _ = buildinfo.Read

type Interface interface {
	Read(r io.ReaderAt) (*debug.BuildInfo, error)
	ReadFile(name string) (info *debug.BuildInfo, err error)
}

type Impl struct{}

func (*Impl) Read(r io.ReaderAt) (*debug.BuildInfo, error) {
	return buildinfo.Read(r)
}
func (*Impl) ReadFile(name string) (info *debug.BuildInfo, err error) {
	return buildinfo.ReadFile(name)
}
