// Code generated by a tool. DO NOT EDIT.

// Package md5 provides a mockable wrapper for crypto/md5.
package md5

import (
	md5 "crypto/md5"
	hash "hash"
)

var _ Interface = &Impl{}
var _ = md5.New

type Interface interface {
	New() hash.Hash
	Sum(data []byte) [16]byte
}

type Impl struct{}

func (*Impl) New() hash.Hash {
	return md5.New()
}
func (*Impl) Sum(data []byte) [16]byte {
	return md5.Sum(data)
}
