// Code generated by a tool. DO NOT EDIT.

// Package aes provides a mockable wrapper for crypto/aes.
package aes

import (
	aes "crypto/aes"
	cipher "crypto/cipher"
)

var _ Interface = &Impl{}
var _ = aes.NewCipher

type Interface interface {
	NewCipher(key []byte) (cipher.Block, error)
}

type Impl struct{}

func (*Impl) NewCipher(key []byte) (cipher.Block, error) {
	return aes.NewCipher(key)
}
