// Code generated by a tool. DO NOT EDIT.

// Package printer provides a mockable wrapper for go/printer.
package printer

import (
	printer "go/printer"
	token "go/token"
	io "io"
)

var _ Interface = &Impl{}
var _ = printer.Fprint

type Interface interface {
	Fprint(output io.Writer, fset *token.FileSet, node any) error
}

type Impl struct{}

func (*Impl) Fprint(output io.Writer, fset *token.FileSet, node any) error {
	return printer.Fprint(output, fset, node)
}
