// Code generated by a tool. DO NOT EDIT.

// Package pe provides a mockable wrapper for debug/pe.
package pe

import (
	pe "debug/pe"
	io "io"
)

var _ Interface = &Impl{}
var _ = pe.NewFile

type Interface interface {
	NewFile(r io.ReaderAt) (*pe.File, error)
	Open(name string) (*pe.File, error)
}

type Impl struct{}

func (*Impl) NewFile(r io.ReaderAt) (*pe.File, error) {
	return pe.NewFile(r)
}
func (*Impl) Open(name string) (*pe.File, error) {
	return pe.Open(name)
}
