// Code generated by a tool. DO NOT EDIT.

// Package suffixarray provides a mockable wrapper for index/suffixarray.
package suffixarray

import (
	suffixarray "index/suffixarray"
)

var _ Interface = &Impl{}
var _ = suffixarray.New

type Interface interface {
	New(data []byte) *suffixarray.Index
}

type Impl struct{}

func (*Impl) New(data []byte) *suffixarray.Index {
	return suffixarray.New(data)
}
