// Code generated by a tool. DO NOT EDIT.

// Package user provides a mockable wrapper for os/user.
package user

import (
	user "os/user"
)

var _ Interface = &Impl{}
var _ = user.Current

type Interface interface {
	Current() (*user.User, error)
	Lookup(username string) (*user.User, error)
	LookupGroup(name string) (*user.Group, error)
	LookupGroupId(gid string) (*user.Group, error)
	LookupId(uid string) (*user.User, error)
}

type Impl struct{}

func (*Impl) Current() (*user.User, error) {
	return user.Current()
}
func (*Impl) Lookup(username string) (*user.User, error) {
	return user.Lookup(username)
}
func (*Impl) LookupGroup(name string) (*user.Group, error) {
	return user.LookupGroup(name)
}
func (*Impl) LookupGroupId(gid string) (*user.Group, error) {
	return user.LookupGroupId(gid)
}
func (*Impl) LookupId(uid string) (*user.User, error) {
	return user.LookupId(uid)
}
