// Code generated by a tool. DO NOT EDIT.

// Package crypto provides a mockable wrapper for crypto.
package crypto

import (
	crypto "crypto"
	hash "hash"
)

var _ Interface = &Impl{}
var _ = crypto.RegisterHash

type Interface interface {
	RegisterHash(h crypto.Hash, f func() hash.Hash)
}

type Impl struct{}

func (*Impl) RegisterHash(h crypto.Hash, f func() hash.Hash) {
	crypto.RegisterHash(h, f)
}
