// Code generated by a tool. DO NOT EDIT.

// Package format provides a mockable wrapper for go/format.
package format

import (
	format "go/format"
	token "go/token"
	io "io"
)

var _ Interface = &Impl{}
var _ = format.Node

type Interface interface {
	Node(dst io.Writer, fset *token.FileSet, node any) error
	Source(src []byte) ([]byte, error)
}

type Impl struct{}

func (*Impl) Node(dst io.Writer, fset *token.FileSet, node any) error {
	return format.Node(dst, fset, node)
}
func (*Impl) Source(src []byte) ([]byte, error) {
	return format.Source(src)
}
