// Code generated by a tool. DO NOT EDIT.

// Package jpeg provides a mockable wrapper for image/jpeg.
package jpeg

import (
	image "image"
	jpeg "image/jpeg"
	io "io"
)

var _ Interface = &Impl{}
var _ = jpeg.Decode

type Interface interface {
	Decode(r io.Reader) (image.Image, error)
	DecodeConfig(r io.Reader) (image.Config, error)
	Encode(w io.Writer, m image.Image, o *jpeg.Options) error
}

type Impl struct{}

func (*Impl) Decode(r io.Reader) (image.Image, error) {
	return jpeg.Decode(r)
}
func (*Impl) DecodeConfig(r io.Reader) (image.Config, error) {
	return jpeg.DecodeConfig(r)
}
func (*Impl) Encode(w io.Writer, m image.Image, o *jpeg.Options) error {
	return jpeg.Encode(w, m, o)
}
